config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users do
    resources :posts, shallow: true
  end

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  belongs_to :user
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :content
  validates :content, length: { maximum: 170 }
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :first_name, :last_name, :password
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.first
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    user = User.find(params[:user_id])
    @posts = user.posts
  end

  def show
    @post = current_user.posts.find params[:id]
  end

  def create
    post = current_user.posts.create!(title: params[:title], content: params[:content])
    redirect_to user_posts_path(current_user.id)
  end

  def edit
  end

  def update
    post = Post.find(params[:id])
    post.update(title: params[:title], content: params[:content])
    redirect_to user_posts_path(current_user.id)
  end

  def destroy
    if current_user
      post = current_user.posts.find params[:id]
      post.destroy
      redirect_to user_posts_path(current_user.id)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
  end

  def create
  end

  def edit
  end

  def updated
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Micropost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
Edit
<%= form_tag post_path, method: :patch do %>
  <input type="text" placeholder="Title" name="title">
  <input type="text" placeholder="Content" name="content">
  <button>Save</button>
<% end %>

app/views/posts/index.html.erb
Post Index
<ul>
  <% @posts.each do |post| %>
  <li>
    <%= post.title %>
    <%= post.content %>
    <%= post.updated_at.to_date %>
    <%= button_to "X", post_path(post.id), method: :delete %>
    <%= link_to "Edit", edit_post_path(post.id) %>

  </li>
  <% end %>
</ul>

  <%= link_to "New Post", new_user_post_path %>

app/views/posts/new.html.erb
New Post
<%= form_tag user_posts_path do %>
  <input type="text" placeholder="Title" name="title">
  <input type="text" placeholder="Content" name="content">
  <button>Save</button>
<% end %>

app/views/posts/show.html.erb
Show Post

<%= @post.content %>

app/views/users/index.html.erb
Users Index
<ul>
  <% @users.each do |user| %>
  <li>
    <%= user.first_name %>
    <%= user.last_name %>
    <%= link_to "posts", user_posts_path(user.id) %>
  </li>
  <% end %>
</ul>